[package]
name = "chachat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
bytes = "1.1.0"
mio = "0.6.23"
mio-extras = "2.0.6"
